image: archlinux/base:latest

stages:
  - check

before_script:
  - echo -e "[glarch]\nSigLevel = Never\nServer = hhttps://gitlab.com/glatan/pkgbuild/-/raw/master/release/\n" >> /etc/pacman.conf
  - pacman -Syyu --noconfirm
  - pacman -S --noconfirm awk jq

Check_Update:
  stage: check
  only:
    refs:
      - master
  script:
    - script/check_update.sh
